name: fmls-beam-control
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - gym
    - tensorflow
    - keras
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - scipy
    - tqdm
    - jupyter
    - git+https://github.com/google/qkeras#egg=qkeras
